env:
  browser: true
  es2020: true
extends:
  - plugin:react/recommended
  - google
  - prettier
  - prettier/react
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  require-jsdoc: 0
  react/prop-types: 0
