stages:
  - test

test:
  stage: test
  environment:
    name: test
  only:
    - master
  script:
    - npm run install
    - npm run build
    - npm install firebase-tools
    - firebase use --token $FIREBASE_DEPLOY_KEY labspoon-test
    - firebase deploy -m "pipeline $CI_PIPELINE_ID build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY